title: Johan Groenen
subtitle: Ook beginnen met open source ontwikkelen? Neem contact op!
img: https://www.jgroenen.nl/img/jgroenen.png
url: https://www.jgroenen.nl
keywords: kwartiermaker, open samenwerking, digitale transformatie, innovatie, publictech
twitter_user: "@jpagroenen"
quote: alles is inspiratie
description: "Open samenwerking en open source ontwikkeling van publieke digitale producten en diensten"

collections:
  aantekeningen:
    output: true
    permalink: /aantekeningen/:year/:month/:day/:title/
  kaarten:
    output: true
    permalink: /kaarten/:name/
  projecten:
    output: true

defaults:
  - scope:
      type: kaarten
    values:
      layout: default
      collection: kaarten
  - scope:
      type: aantekeningen
    values:
      layout: aantekening
      collection: aantekeningen
  - scope:
      type: projecten
    values:
      layout: aantekening
      collection: projecten